# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uitail < Formula
  desc ""
  homepage "https://github.com/marhaupe/uitail"
  version "0.0.2"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/marhaupe/uitail/releases/download/v0.0.2/uitail_Darwin_x86_64.tar.gz"
      sha256 "9b3d0659c5942c65f1a50ee0a6e5cfc9fd9dd67e042e4aefaadd4e7f1c39a322"

      def install
        bin.install "uitail"
      end
    end
    on_arm do
      url "https://github.com/marhaupe/uitail/releases/download/v0.0.2/uitail_Darwin_arm64.tar.gz"
      sha256 "64b071edfc6d83ae1c40cedddf0c3b631dcd669e6ddfe2c433f15ef6ad5b8469"

      def install
        bin.install "uitail"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marhaupe/uitail/releases/download/v0.0.2/uitail_Linux_x86_64.tar.gz"
        sha256 "9079775c8c093ef6af5800593a3fc93d5cd37e6b4a25a5f27ab22b1aaa6f73af"

        def install
          bin.install "uitail"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marhaupe/uitail/releases/download/v0.0.2/uitail_Linux_arm64.tar.gz"
        sha256 "84c96739e99ea5de48f7ec5ce775dc3ccc6d52fec9a713bf3b343fd27c85e8bb"

        def install
          bin.install "uitail"
        end
      end
    end
  end
end
