# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uitail < Formula
  desc ""
  homepage "https://github.com/marhaupe/uitail"
  version "0.0.8"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/marhaupe/uitail/releases/download/v0.0.8/uitail_Darwin_x86_64.tar.gz"
      sha256 "d8540e47791ff4b37feae8e4bc88e54a5b4c5a30c9ff30123fee740c38f3334a"

      def install
        bin.install "uitail"
      end
    end
    on_arm do
      url "https://github.com/marhaupe/uitail/releases/download/v0.0.8/uitail_Darwin_arm64.tar.gz"
      sha256 "779f2cd88cbf286c0a889e8c071d2937c378af02438fe157b45d3b752b732b59"

      def install
        bin.install "uitail"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marhaupe/uitail/releases/download/v0.0.8/uitail_Linux_x86_64.tar.gz"
        sha256 "b34a1eabdf12c54a48333120298cf704ca359656e825d6c8d8d3476ac431d7c9"

        def install
          bin.install "uitail"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marhaupe/uitail/releases/download/v0.0.8/uitail_Linux_arm64.tar.gz"
        sha256 "0bfeb42e6be28fcb611e48f58934a8da8f35ba3020db0892ca9bf791717516d0"

        def install
          bin.install "uitail"
        end
      end
    end
  end
end
